### ISSUE TITLE
[bug] Creating and signing provenance fails because retrieving signed certificate fails.

### ISSUE THREAD

**Issue by jenstroeger** [slsa-framework/slsa-github-generator#1163]
**Describe the bug**

Creating signed provenance fails with
```
##[debug]/usr/bin/bash --noprofile --norc -e -o pipefail /home/runner/work/_temp/12f3ed8f-b71f-4b24-816e-9adc5a6a9d03.sh
Retrieving signed certificate...

        Note that there may be personally identifiable information associated with this signed artifact.
        This may include the email address associated with the account with which you authenticate.
        This information will be used for signing this artifact and will be stored in public transparency logs and cannot be removed later.
validating log entry: unable to fetch Rekor public keys from TUF repository, and not trusting the Rekor API for fetching public keys: updating local metadata and targets: error updating to TUF remote mirror: tuf: invalid key
remote status:{
	"mirror": "sigstore-tuf-root",
	"metadata": {
		"root.json": {
			"version": 5,
			"len": 6388,
			"expiration": "18 Apr 23 18:13 UTC",
			"error": ""
		},
		"snapshot.json": {
			"version": 53,
			"len": 1973,
			"expiration": "10 Nov 22 21:10 UTC",
			"error": ""
		},
		"targets.json": {
			"version": 5,
			"len": 4188,
			"expiration": "18 Apr 23 18:13 UTC",
			"error": ""
		},
		"timestamp.json": {
			"version": 53,
			"len": 719,
			"expiration": "03 Nov 22 21:10 UTC",
			"error": ""
		}
	}
}
Error: Process completed with exit code 1.
##[debug]Finishing: Create and sign provenance
```

**To Reproduce**

This happens in a private repository, based on the [this job](https://github.com/jenstroeger/python-package-template/blob/f41b0e6a46061081370253b9ac17a1b62b5c85dc/.github/workflows/release.yaml#L67-L77):
```yaml
  provenance:
    needs: build
    # The generator should be referenced with a semantic version.
    # The build will fail if we reference it using the commit sha.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.2.0
    with:
      base64-subjects: ${{ needs.build.outputs.artifacts-sha256 }}
    permissions:
      actions: read # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
```

**Expected behavior**

Finish successfully.

**Screenshots**

**Additional context**

I’m going to be honest: I’m trying to convince people in my org to integrate SLSA into the CI and build processes, but it’s getting harder when the actions break with different issues every other week.

I just updated to v1.2.1 and hope that’ll work.

**Comment by jenstroeger** [comment]
And v1.2.1 fails with
```
Error: some/repo: Repository is private. The workflow has halted in order to keep the repository name from being exposed in the public transparency log. Set 'private-repository' to override.
```
which isn’t documented. So based on [the src](https://github.com/slsa-framework/slsa-github-generator/blob/d6404facaab3685905f9105f2ce4b31e897bf68f/.github/workflows/generator_generic_slsa3.yml#L50-L54) I guess I need to use
```yaml
    with:
      private-repository: true
```
and that means that the _name_ of the repository “leaks”… where?

**Comment by ianlewis** [comment]
> And v1.2.1 fails with
> 
> ```
> Error: some/repo: Repository is private. The workflow has halted in order to keep the repository name from being exposed in the public transparency log. Set 'private-repository' to override.
> ```
> 
> which isn’t documented. So based on [the src](https://github.com/slsa-framework/slsa-github-generator/blob/d6404facaab3685905f9105f2ce4b31e897bf68f/.github/workflows/generator_generic_slsa3.yml#L50-L54) I guess I need to use
> 
> ```yaml
>     with:
>       private-repository: true
> ```
> 
> and that means that the _name_ of the repository “leaks”… where’s that transparency log accessible?

Yeah, forgetting to add that to the docs was an oversight on our part. The reason for it is that the repository name is uploaded as part of the transparency log entry. This might be considered a "leak" if the repo is private but you can explicitly opt-in if you are ok with that. I will create a PR to document it today.

For those who don't want repo names to leak on the public Rekor instance, we have an issue to track support for using a private Rekor instance (#34) and we may prioritize adding that now that Rekor 1.0 was released and the API and public instance will hopefully be a bit more stable. It's been a big concern for us so we've been working with that team to figure out ways to catch issues earlier so they don't end up affecting users.

**Comment by jenstroeger** [comment]
@ianlewis thanks for the answer, adding `private-repository` worked.

However, I want to emphasize that this bug still applies to v1.2.0 and a [fix](https://www.conventionalcommits.org/en/v1.0.0/) update & bump to v1.2.1 should _not_ leave behind a broken service!

**Comment by ianlewis** [comment]
Thanks for the feedback. We'll try to adhere to semantic versioning better going forward.

**Comment by jenstroeger** [comment]
@ianlewis what are you saying? That you folks _intentionally_ broke v1.2.0? You’ve changed this issue to a documentation change… what’s with the invalid key that fails the generator?

**Comment by ianlewis** [comment]
I'm saying that the `private-repository` input is working as intended. It's an opt in flag for users to indicate that it's ok for private repository names to be uploaded to the public transparency log.

However, since it wasn't a simple bugfix upgrade from v1.2.0 to v1.2.1 without adding that input we probably should have set the version at 1.3.0 to indicate that.

**Comment by jenstroeger** [comment]
Regarding [v1.2.0](https://github.com/slsa-framework/slsa-github-generator/releases/tag/v1.2.0): is that version dead and deprecated, or is it supposed to be functioning (because it isn’t, hence this bug report).

**Comment by ianlewis** [comment]
Ok, I see. Sorry for the confusion. Yes. Version v1.2.0 is broken for reasons that are outside the scope of this project and is not likely to get fixed.

I'll try to add some more doc to communicate that better.

**Comment by jenstroeger** [comment]
> Yes. Version v1.2.0 is broken for reasons that are outside the scope of this project and is not likely to get fixed.

So… the supply-chain tools are broken by their own supply chain? Ironic.

**Comment by ianlewis** [comment]
> > Yes. Version v1.2.0 is broken for reasons that are outside the scope of this project and is not likely to get fixed.
> 
> So… the supply-chain tools are broken by their own supply chain? Ironic.

Indeed... We're working with them to improve things and catch them before they become a problem but they've been moving fast...

**Comment by ianlewis** [comment]
I added a note to the [v1.2.0](https://github.com/slsa-framework/slsa-github-generator/releases/tag/v1.2.0) release indicating that users should upgrade.

**Comment by jenstroeger** [comment]
Frankly, that’s _very disagreeable and frustrating_ 🙁

I suggest keeping the title of the issue as it was so people who still use v1.2.0 and who will now run into this problem can find this issue.

Adding documentation to the v1.2.1 docs regarding the `private-repository` should be separate from this rather monumental problem here.

**Comment by ianlewis** [comment]
Ok, I'll create a separate issue for that. Sorry for all the confusion. I misunderstood your core problem and thought this was more of a documentation issue.

**Comment by ianlewis** [comment]
@jenstroeger Were you able to try it with v1.2.1? I'm now seeing failures like yours for v1.2.1 as well...

```
FAILED: SLSA verification failed: could not find a matching valid signature entry: got unexpected errors updating local metadata and targets: error updating to TUF remote mirror: tuf: invalid key
```

https://github.com/slsa-framework/slsa-github-generator/actions/runs/3334679611/jobs/5517919607

**Comment by jenstroeger** [comment]
@ianlewis we’ve enabled `compile-generator` ever since issue https://github.com/slsa-framework/slsa-github-generator/issues/942, so running v1.2.1 worked for me.

**Comment by ianlewis** [comment]
@jenstroeger Yeah, I'll probably just go ahead and document it (#1166). It was really only meant for our pre-submit tests because this kind of issue with Rekor is never supposed to happen but here we are...

**Comment by asraa** [comment]
> Were you able to try it with v1.2.1? I'm now seeing failures like yours for v1.2.1 as well..

I can chime in very quick but am travelling after a conference :|

Sigstore was using a non-compliant TUF rootversion, and a compliant version got pushed last night. 

The old libs sigstore (Go) was using to get the root verification material did not support compliant versions. I can update later, but this problem wasn't detected in our release workflows because we don't test sigstore root layouts (@kpk47 testing against pre-prod would have caught these issues, but only given us a 3 day window to fix issues). Sigstore's TUF root is inherently moving and has breaking changes because of using broken underlying libraries.

We'll be able to fix, at least, I can relay and have plans to push the TUF root changes to staging (which gives a lot more of a window than pre-prod).

**Comment by rbehjati** [comment]
I am seeing [the same error on Oak](https://github.com/project-oak/oak/actions/runs/3336789782/jobs/5522515428). But Oak is a public repository. We are using v1.2.0. Does updating to v1.2.1 solve the problem?

**Comment by asraa** [comment]
> I am seeing [the same error on Oak](https://github.com/project-oak/oak/actions/runs/3336789782/jobs/5522515428). But Oak is a public repository. We are using v1.2.0. Does updating to v1.2.1 solve the problem?

Yes, but also with the option `compile-generator: true`.

**Comment by FrimIdan** [comment]
@ianlewis I've got the same error on a private repo with the following configuration
```
    needs: [build]
    permissions:
      actions: read
      id-token: write
      # contents: read
      packages: write
    if: startsWith(github.ref, 'refs/tags/')
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.2.1
    with:
      image: ${{ needs.build.outputs.image }}
      digest: ${{ needs.build.outputs.digest }}
      registry-username: ${{ github.actor }}
      compile-generator: true
      private-repository: true
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
```

Was the issue solved only in the generic generator and no in the container generator?

**Comment by ianlewis** [comment]
@FrimIdan Which error are you getting? You should not get the `tuf: invalid key` error if you use `compile-generator: true` and you should not get the `Repository is private` error if you use `private-repository: true`. Knowing which error you are getting will help us track down the cause.

**Comment by FrimIdan** [comment]
@ianlewis i've got `tuf: invalid key` and i'm using `compile-generator: true`
```
Note that there may be personally identifiable information associated with this signed artifact.
        This may include the email address associated with the account with which you authenticate.
        This information will be used for signing this artifact and will be stored in public transparency logs and cannot be removed later.
Error: signing XXX@sha256:XXX: getting signer: getting key from Fulcio: verifying SCT: updating local metadata and targets: error updating to TUF remote mirror: tuf: invalid key
remote status:{
	"mirror": "https://sigstore-tuf-root.storage.googleapis.com/",
	"metadata": {
		"root.json": {
			"version": 5,
			"len": 6388,
			"expiration": "18 Apr 23 18:13 UTC",
			"error": ""
		},
		"snapshot.json": {
			"version": 53,
			"len": 1973,
			"expiration": "10 Nov 22 21:10 UTC",
			"error": ""
		},
		"targets.json": {
			"version": 5,
			"len": 4188,
			"expiration": "18 Apr 23 18:13 UTC",
			"error": ""
		},
		"timestamp.json": {
			"version": 53,
			"len": 719,
			"expiration": "03 Nov 22 21:10 UTC",
			"error": ""
		}
	}
}
main.go:62: error during command execution: XXX@sha256:XXX: getting signer: getting key from Fulcio: verifying SCT: updating local metadata and targets: error updating to TUF remote mirror: tuf: invalid key
remote status:{
	"mirror": "https://sigstore-tuf-root.storage.googleapis.com",
	"metadata": {
		"root.json": {
			"version": 5,
			"len": 6388,
			"expiration": "18 Apr 23 18:13 UTC",
			"error": ""
		},
		"snapshot.json": {
			"version": 53,
			"len": 1973,
			"expiration": "10 Nov 22 21:10 UTC",
			"error": ""
		},
		"targets.json": {
			"version": 5,
			"len": 4188,
			"expiration": "18 Apr 23 18:13 UTC",
			"error": ""
		},
		"timestamp.json": {
			"version": 53,
			"len": 719,
			"expiration": "03 Nov 22 21:10 UTC",
			"error": ""
		}
	}
}
Error: Process completed with exit code 1.
```

**Comment by ianlewis** [comment]
Thanks. It looks like older versions of cosign were affected by the Fulcio TUF roots being rotated though they said it shouldn't be. I'll update it now so it's available when we put out the next release which should be soon.

**Comment by ianlewis** [comment]
@FrimIdan I verified that the https://github.com/slsa-framework/slsa-github-generator/pull/864 fixes the issue by updating cosign in the workflow. It should be fixed in the next workflow release.

**Comment by FrimIdan** [comment]
@ianlewis I can confirm that using `slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@main` solved the problem. Thanks!

**Comment by ddworken** [comment]
I also ran into this issue. Upgrading to v1.2.1 and updating to the latest slsa-verifier "fixed" the issue. Though I only say "fixed" since this means existing deploys are currently stranded because:

1. They currently have the older slsa-verifier 
2. Per the above, there is no way to have the old slsa-verifier accept newly generated signatures
3. Thus, there is no way to upgrade existing deploys to accept newly generated signatures 

So this class of issue is pretty severe for projects using SLSA for updates. From my perspective, I have a few options:

1. Continue using SLSA and risk stranding users on broken versions 
2. Support an opt-out where if SLSA fails, the user is told "This may be dangerous, or there may just be another SLSA bug. Do you want to proceed with the update?"
3. Have a side channel where if an API endpoint I control says to disable SLSA, SLSA is disabled
4. Drop using SLSA

Originally, I did option 1. After https://github.com/slsa-framework/slsa-verifier/issues/285 I swapped to option 2 and at this point I'm leaning towards going for option 3 (at least until things have stabilized more).

**Comment by behnazh-w** [comment]
In this context returning the exit code to let the caller control the failure would be helpful: https://github.com/slsa-framework/slsa-github-generator/issues/1177

**Comment by gal-legit** [comment]
Getting the same kind of errors with the go builder for a private repository:
```
  # Trusted builder.
  build:
    permissions:
      id-token: write # To sign the provenance.
      contents: write # To upload assets to release.
      actions: read # To read the workflow path.
    needs: args
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@1.2.2
    with:
      go-version: 1.17
      # Optional: only needed if using ldflags.
      evaluated-envs: "COMMIT_DATE:${{needs.args.outputs.commit-date}}, COMMIT:${{needs.args.outputs.commit}}, VERSION:${{needs.args.outputs.version}}, TREE_STATE:${{needs.args.outputs.tree-state}}"
      private-repository: true
```

Referencing either v1.2.2 or main results in:
```
Run ./__BUILDER_CHECKOUT_DIR__/.github/actions/generate-builder/generate-builder.sh
Fetching the builder with ref: refs/tags/v1.2.2
./__BUILDER_CHECKOUT_DIR__/.github/actions/generate-builder/generate-builder.sh: line 22: .github/actions/generate-builder/builder-fetch.sh: No such file or directory
Error: Process completed with exit code 127.
```

Referencing v1.2.1 results in:
```
unable to fetch Rekor public keys from TUF repository: verifying tlog entry 24296fb24b8ad77a09fe522f9a80b80e39769fce01ccb678e76b740491c5c3a7b1e22978ff0fa541
```
