### ISSUE TITLE
[feature] pre-submit input flag

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#1167]
We should add a check to verify that workflows are running at a release tag. Currently `compile-generator` was meant to serve that purpose but due to stability issues with Rekor's public instance we are forced to use compiling the builders/generators as a workaround.

While compiling the builders & generators is not ideal because it takes longer it's not necessarily a problem other than it takes a long time.

However, `compile-generator` and `compile-builder` also allow you to run the workflows with non-release references.

```yaml
  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@main
    with:
      base64-subjects: "${{ needs.build.outputs.digest }}"
      compile-generator: true
```

This will run the workflow at main with the latest checkout. The `slsa-verifier` will fail to verify the provenance because the ref is not a semver compatible tag but the builder/generator workflows will succeed. This may potentially become a security issue as we don't really guarantee functionality or security at random commits. It will also potentially be a usability issue because users might be confused that they can generate SLSA this way but they can't verify it.
