### ISSUE TITLE
[feature] Return exit code instead of failing jobs

### ISSUE THREAD

**Issue by behnazh-w** [slsa-framework/slsa-github-generator#1177]
**Is your feature request related to a problem? Please describe.**
Because GHA does not support [`continue-on-error`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error ) at `job` level, it's hard to add constraints based on the reusable workflow SLSA generator's success or failure. At the moment when the generator job fails, the caller workflow is marked as failed too. 

It would be useful to return the exit code as output instead of failing the job and allow the caller to decide to fail the workflow and take action.

**Comment by ianlewis** [comment]
I think there is a job level [`jobs.<job_id>.continue-on-error`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error). I believe you can check the result via the [`needs`](https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context) context. Does that solve your problem?

**Comment by behnazh-w** [comment]
Do you know how to make it work with reusable workflows? This is not a valid GHA:

```yaml
  provenance:
    needs: [build, release]
    continue-on-error: true
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.2.1
    with:
      base64-subjects: ${{ needs.build.outputs.artifacts-sha256 }}
      private-repository: true
      compile-generator: true
    permissions:
      actions: read # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
```
