### ISSUE TITLE
[feature] registry-username should be a secret

### ISSUE THREAD

**Issue by sebhoss** [slsa-framework/slsa-github-generator#1347]
**Is your feature request related to a problem? Please describe.**

The `registry-username` input of the generator_container_slsa3 workflow is declared as input which prohibits using secrets as values. The following example fails:

```yaml
  provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.4.0
    with:
      registry-username: ${{ secrets.DOCKER_USERNAME }} # NOT ALLOWED
    secrets:
      registry-password: ${{ secrets.DOCKER_PASSWORD }}
```

**Describe the solution you'd like**

The `registry-username` input should be a secret. Example workflow should look liks this:

```yaml
  provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.4.0
    secrets:
      registry-username: ${{ secrets.DOCKER_USERNAME }}
      registry-password: ${{ secrets.DOCKER_PASSWORD }}
```

**Describe alternatives you've considered**

I thought about publishing slsa data in ghcr but it feels weird when everything else is in dockerhub.

**Additional context**

This is only relevant when you are NOT using ghcr to publish images.

**Comment by laurentsimon** [comment]
Hi @sebhoss thanks for the report. I agree we should not force users to expose their usernames.

Can you tell us more about the risk you have in mind:
1. The username is not redacted from the logs?
2. The username is available from the source code in your repo.
3. Both?

**Comment by sebhoss** [comment]
Hey thanks for getting back to me. My initial concern was really more about an usability issue that stops me from using a variable instead of hard-coding my username in multiple repositories within a single GitHub organization. Declaring the username as a secret would allow me to use the 'secrets' mechanism that GitHub currently offers. The `docker/login-action` uses the same idea in its initial example at https://github.com/docker/login-action#docker-hub and I'm guessing that lots of people have a setup very similar to that. However, they cannot re-use the same (secret) variables to configure the action from this repository because they will get an error similar to this:

```shell
Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.DOCKER_USERNAME
```

By declaring the username of this action a secret, the workflow config could look like this:

```yaml
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      ...
  provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.4.0
    secrets:
      registry-username: ${{ secrets.DOCKER_USERNAME }}
      registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
```

I could not find a lot of documentation why reusable workflows make this distinction between inputs and secrets but it's causing an inconsistency in workflow configuration and might frustrate adopters of the slsa actions.

That said, https://github.com/github/roadmap/issues/575 sounds like a great solution as well and I'm fine with waiting for that to land - feel free to close this ticket!

**Comment by laurentsimon** [comment]
Thanks for the explanation. We'll make sure to update our doc once https://github.com/github/roadmap/issues/575 is landed.
The problem you're encountering is that reusable workflows are isolated so env variables and secrets are not available by default.

Here are options to consider in the meantime:
1. use of `inherit` https://github.blog/changelog/2022-05-03-github-actions-simplify-using-secrets-with-reusable-workflows/. I'n not 100% sure this will work, but give it a try and let us know.
2. declare a second job to set the variable:
```yaml
jobs:
  username:
    outputs:
      username: ${{ steps.username.outputs.value }}
    runs-on: ubuntu-latest
    steps:
      # WARNING: please verify this works. Will the secrets be redacted?
      - run: echo "value=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_OUTPUT
         id: username
  login:
    needs: [username]
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ needs.username.outputs.username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      ...
  provenance:
    needs: [username]
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.4.0
    secrets:
      registry-username: ${{ needs.username.outputs.username }}
      registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
```

Let me know if any of these work. The second option is not great UX-wise :/

@ianlewis any other ideas?

**Comment by vincentgoat** [comment]
I've tried the workaround, but still did not work.
https://github.com/vincentgoat/kubeedge/actions/runs/3754855275/workflow

**Comment by ianlewis** [comment]
Yeah, `set-output` skips output of the username because the value might contain a secret so the workaround won't work.

This is a separate downside of putting usernames in secrets. GitHub will sanitize the output of anything with the username in it.

**Comment by sebhoss** [comment]
I think there is at least one exception for public usernames: An AWS Access Key ID can be used when pushing into ECR repositories and those keys are part of GitHub secrets scanning feature (https://docs.github.com/en/code-security/secret-scanning/secret-scanning-patterns#supported-secrets-for-partner-alerts). This prohibits you from writing that key as plain text into your repository.

**Comment by ianlewis** [comment]
> I think there is at least one exception for public usernames: An AWS Access Key ID can be used when pushing into ECR repositories and those keys are part of GitHub secrets scanning feature (https://docs.github.com/en/code-security/secret-scanning/secret-scanning-patterns#supported-secrets-for-partner-alerts). This prohibits you from writing that key as plain text into your repository.

I've only ever seen the [`aws ecr get-login-password` method](https://docs.aws.amazon.com/AmazonECR/latest/userguide/getting-started-cli.html#cli-authenticate-registry) for logging into the ECR registry, where the username is "AWS". In that case you use the AWS access key id for the username and secret access key for the password? Is that documented somewhere?

**Comment by sebhoss** [comment]
Yeah I think the recommend practice is NOT to use access keys but rather that assume-role stuff. The usage of an access key is documented/shown at https://github.com/docker/login-action#aws-elastic-container-registry-ecr

**Comment by ianlewis** [comment]
Yeah, fair enough. I think the Access key ID is enough of a secret value that you'd want to keep it in a secret (though at least using the `aws` CLI is the preferred method).

BTW, My comment above was referring to the fact that, on the other hand, if you use secrets to hold usernames like "AWS" when using the `aws` CLI method, then GitHub will sanitize and skip output of any values in the workflow that have the value "AWS" in them, sometimes causing massive breakage.

**Comment by ianlewis** [comment]
Hey all,

As a heads-up, we'll likely be reverting the `repository-username` input (as it has not been released yet) that we added and asking folks to use the new [support for configuration variables](https://github.blog/changelog/2023-01-10-github-actions-support-for-configuration-variables-in-workflows/) to store the repository username. This is just to keep our workflow API cleaner since Github supports variables natively now.

You can add it to your repository's environment and access it using `vars`.

```yaml
  provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.4.0
    with:
      registry-username: ${{ vars.DOCKER_USERNAME }}
    secrets:
      registry-password: ${{ secrets.DOCKER_PASSWORD }}
```
