### ISSUE TITLE
[feature][byob] Public Action to share files with builder

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#1576]
Builders / Actions often times require to work on files that are generated as part of a release process, e.g. an SBOM generator may take as input a binary which is not in the repo.

We may need to expose a public Action to "share" these files with the trusted builder. Something along the lines of:
```yaml
uses: slsa-framework/actions/delegator/share-artifacts@v1.2.3
with:
  files: |
     /path/to/file1
     /path/to/some/files/*
```

The way I imagine this to work is that it will create a JSON output listing the files (+ hashes) that were uploaded. Something like:

```yaml
{
 version: 1
 files: [
   {
     "name": <randomized-value>,
     "path": <the-path>,
     "sha256": <value>
  },
  ...
 ]
```

When calling a TRW, users can add these as an additional input:

```yaml
uses: path/to/trw_slsa3.yaml
with:
  share-artifacts: ${{ needs.<job1>.outputs.artifacts }}, ${{ needs.<job2>.outputs.artifacts }}
```
