### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by rbehjati** [slsa-framework/slsa-github-generator#1685]
**Describe the bug**
I am trying to use [builder_docker-based_slsa3.yml]() in Oak (see [this PR](https://github.com/project-oak/oak/pull/3669)), and there is problem in the `generate-builder` step. 

Here is the error ([the Action](https://github.com/project-oak/oak/actions/runs/4263246828/jobs/7419761814)):
```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/oak/oak/__BUILDER_CHECKOUT_DIR__/.github/actions/privacy-check'. Did you forget to run actions/checkout before running your local action?
```

I believe the point of this step is to generate the Docker-based builder binary, but the following parameters are passed to the action, which does not seem right:
```
with:
    repository: rbehjati/oak
    ref: bbe9bf9844c845d0b1b2fb2e50c86e2a123c6324
    go-version: 1.19
    binary: slsa-builder-docker-linux-amd64
    compile-builder: true
    directory: internal/builders/docker
    allow-private-repository: false
    token: ***
```

**To Reproduce**
See the PR linked above.

**Expected behavior**
No error.

**Screenshots**
-- 

**Additional context**
--
