### ISSUE TITLE
[bug] Token validation error

### ISSUE THREAD

**Issue by AdamKorcz** [slsa-framework/slsa-github-generator#1703]
**Describe the bug**
I have the following workflow:
```yaml
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - name: Print something
      run: echo "hello"
  slsa-setup:
    permissions:
      id-token: write # For token creation.
    outputs:
      slsa-token: ${{ steps.generate.outputs.slsa-token }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate the token
        id: generate
        uses: slsa-framework/slsa-github-generator/actions/delegator/setup-token@main
        with:
          slsa-workflow-recipient: "delegator_generic_slsa3.yml"
          slsa-rekor-log-public: ${{ inputs.rekor-log-public }}
          slsa-runner-label: "ubuntu-latest"
          slsa-build-action-path: "./builder"
          slsa-workflow-inputs: ${{ toJson(inputs) }}
      - name: run echo after slsa-setup
        run: echo "echo after slsa-setup"
  slsa-run:
    needs: [slsa-setup]
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read   # For the entrypoint.
      packages: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/delegator_generic_slsa3.yml@main
    with:
      slsa-token: ${{ needs.slsa-setup.outputs.slsa-token }}
```

When I run it, I get the following error in the `verify-token` step of the generaic delegator: 
`mismatch github.job: got 'slsa-setup', expected 'verify-token'.`

Which looks like it fails here: https://github.com/slsa-framework/slsa-github-generator/blob/4ed6a517a4eda072ff1fc2395f806a82741400a6/.github/actions/verify-token/src/validate.ts#L35

cc @ianlewis since you recently refactored the `verify-token` validation.
