### ISSUE TITLE
[bug] Don't record RUNNER_XXX

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#1817]
We record RUNNER_NAME, RUNNER_OS and RUNNER_IMAGE from the setup-token. These values are taken from the caller, and don't represent the values where the build actually takes place. 

I suggest we remove them. The runner label (if available) can be reported since our re-usable workflows decide which runner to run. (If these values can be retrieved from the workflow, we should report them.)

We may be able to report some of the runner info as resolvedDependencies if the untrusted job reports it, but not sure that's valuable since we don't trust it.

related: I created https://github.com/slsa-framework/slsa/issues/681 to ask for clarification about who populates these

@ianlewis @asraa

**Comment by ianlewis** [comment]
I wonder if we couldn't record the runner info before we run the user's untrusted action in the delegator.

For example:

```yaml
build-artifacts-ubuntu:
  # ...
  outputs:
    runner-name: "${{ steps.record-runner.outputs.runner-name }}"
  steps:
    # ...
    record-runner:
      run: |
        echo "runner-name=${RUNNER_NAME}" >> "$GITHUB_OUTPUT"
    - name: Build artifacts
        id: build-artifacts-action
      # ...
```

This would depend on the fact that the job step where the user's action is run can't overwrite a previous step's outputs.  I'm not sure that's true but it might be worth exploring.
