### ISSUE TITLE
[bug] Strict input checking

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#1907]
GitHub actions don't validate that inputs were passed to an action even if the input is marked as required.

We should be more strict about input checking and produce errors if the inputs were not given.

For example, a call to `secure-project-checkout-go` could omit the `go-version` input even though it's required. This would result in an empty value being passed to `setup-go` which would install the "latest version" as determined by `setup-go`.

```yaml
      - name: Checkout the Go repository                                                                                                                                                                                                                                                                                                                                   
        uses: ./__BUILDER_CHECKOUT_DIR__/.github/actions/secure-project-checkout-go                                                                                                                                                                                                                                                                                        
        with:                                                                                                                                                                                                                                                                                                                                                              
          path: __PROJECT_CHECKOUT_DIR__
```

**Comment by laurentsimon** [comment]
Shall we create an issue on their runner repo?

**Comment by ianlewis** [comment]
> Shall we create an issue on their runner repo?

Seems there is an issue already https://github.com/actions/runner/issues/1070

**Comment by ianlewis** [comment]
In the meantime, it looks like we should use the `required` option on `getInput` when getting required inputs in TypeScript actions.

We should also do explicit checks in composite actions.

Maybe something like:
```yaml
- name: validate inputs
  id: validate-inputs
  env:
    REQUIRED_INPUT: ${{ inputs.required-input }}
  run: |
    if [[ "${REQUIRED_INPUT}" == "" ]]; then
      >&2 echo "required-input is required!"
      exit 1
    fi
```
