### ISSUE TITLE
[docs][nodejs] Example docs for running tests with multiple Node.js versions

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#2288]
Package maintainers often want to run tests with multiple Node.js versions in order to make sure they are still backwards compatible.

We should show an example in the docs about how to run tests before calling our workflow. This will make it clearer to maintainers where they should run tests.

It might be nice to have an example that calls @ljharb's [workflow](https://github.com/ljharb/actions/blob/d9f477827ed71a259056764107f74afc29febcae/.github/workflows/node.yml) since it's short and fairly self-contained.

For example:
```yaml
jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '>= 10'
      type: minors
      command: npm run tests
```
