### ISSUE TITLE
Unable to use `generator_generic_slsa3` workflow with commit checksum

### ISSUE THREAD

**Issue by JAORMX** [slsa-framework/slsa-github-generator#2993]
**Describe the bug**
The GitHub Actions security hardening guide suggests folks to use commit checksums for pinning workflows. Unfortunately, this recommendation doesn't work with the `generator_generic_slsa3` provided by this repository, as it fails downloading the generator binary.

**To Reproduce**
Create a GitHub workflow that calls the `generator_generic_slsa3` as follows:

```
...
  provenance:
    name: Generate provenance (SLSA3)
    needs:
      - release
    permissions:
      actions: read # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@07e64b653f10a80b6510f4568f685f8b7b9ea830 # v1.9.0
    with:
      base64-subjects: "${{ needs.release.outputs.hashes }}"
      upload-assets: true # upload to a new release
```

The result will fail on the final step as such:

 https://github.com/stacklok/frizbee/actions/runs/6943122793/job/18887599496

**Expected behavior**
One should be able to call the workflow with a checksum

**Screenshots**
Here's the first failure that appears:

![image](https://github.com/slsa-framework/slsa-github-generator/assets/145564/8a50ca0f-7d3f-4999-8910-5743cc4c911c)

Here's the output of "generate builder"

![image](https://github.com/slsa-framework/slsa-github-generator/assets/145564/9b0e9bc8-26f6-46e4-b8cc-c8fb00537ee2)

**Additional context**

Digging further into the issue, it seems that the problem comes from the `generator` step, which in turn calls the `slsa-framework/slsa-github-generator/.github/actions/generate-builder@main` action.

The aforementioned action will then attempt to generate the builder via a bash script as such:

```
    - name: Generate builder
      shell: bash
      env:
        # Builder.
        BUILDER_REPOSITORY: slsa-framework/slsa-github-generator # The repository to download the pre-built builder binary from.
        BUILDER_RELEASE_BINARY: "${{ inputs.binary }}" # The name of the pre-built binary in the release assets. This is also used as the final binary name when compiling the builder from source.
        # Verifier
        # NOTE: These VERIFIER_* variables are used in the builder-fetch.sh script for verification of builder
        # release binaries when the compile-builder input is false.
        VERIFIER_REPOSITORY: slsa-framework/slsa-verifier # The repository to download the pre-built verifier binary from.
        VERIFIER_RELEASE_BINARY: slsa-verifier-linux-amd64 # The name of the verifier binary in the release assets.
        VERIFIER_RELEASE_BINARY_SHA256: e81900c9f11a44276e1552afb7c1f6ea7b13ad9c6efdb920d97f23a76659e25f # The expected hash of the verifier binary.
        VERIFIER_RELEASE: v2.4.1 # The version of the verifier to download.

        COMPILE_BUILDER: "${{ inputs.compile-builder }}"
        # NOTE: If a builder reference is specified, then we will download this version of the builder.
        # Otherwise, we use the same tag reference as the detected workflow source reference. This allows
        # pinning the builder binary version at the same as the reuseable workflow reference, and avoids
        # dynamically fetching a builder binary.
        # The builder-ref option can be used to test the scripts at main to download a builder binary at
        # a previous tag.
        BUILDER_REF: "${{ inputs.builder-ref || inputs.ref }}" # The version of the builder to retrieve.
        BUILDER_DIR: "./__BUILDER_CHECKOUT_DIR__/${{ inputs.directory }}"
        # Needed for the gh CLI used in builder-fetch.sh.
        GH_TOKEN: "${{ inputs.token }}"
        # TODO(#2056): Remove testing input.
        SLSA_VERIFIER_TESTING: "${{ inputs.testing }}"
      run: ./__BUILDER_CHECKOUT_DIR__/.github/actions/generate-builder/generate-builder.sh
```

https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/actions/generate-builder/action.yml#L110

Finally, the script itself fails as it expects there to be a tag reference:

```
# Extract version.
if [[ "$BUILDER_REF" != "$PREFIX"* ]]; then
    echo "Invalid ref: $BUILDER_REF. Expected ref of the form refs/tags/vX.Y.Z"
    exit 2
fi
```

https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/actions/generate-builder/builder-fetch.sh#L32

This behavior seems incorrect, as all along the callpath, there are documentation and references that point to the usage of a checksum being valid. e.g. this is from the action that directly calls that script:

```yaml
  ref:
    description: "A fully formed ref (refs/...) or SHA to checkout for the action code."
    required: true
```
