### ISSUE TITLE
Generate provenance failed with `Unable to validate cosign version: 'v1.13.1'`

### ISSUE THREAD

**Issue by Shelley-BaoYue** [slsa-framework/slsa-github-generator#3006]
Hello, I encountered an issue when generating provenance in my own repository. Actually it was previously working fine.  
I'm using version v1.4.0. 
The format I'm using is as follows. 
```
    if: startsWith(github.ref, 'refs/tags/')
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.4.0
    with:
      image: kubeedge/${{ matrix.target }}
      registry-username: ${{ vars.DOCKERHUB_USER_NAME }}
      digest: ${{ needs.publish-image-to-dockerhub.outputs[format('hash-digest-{0}', matrix.target)] }}
```

However, the error I'm currently experiencing is like: 
![image](https://github.com/slsa-framework/slsa-github-generator/assets/48788150/5a90f078-985e-4098-b6e8-fac6dc686a1f)

 and the specific CI link is https://github.com/kubeedge/kubeedge/actions/runs/7018959831/job/19121028811. 
 Could someone please help me and guide me on what to do?
