### ISSUE TITLE
[bug] Opaque failure in `final` step

### ISSUE THREAD

**Issue by woodruffw** [slsa-framework/slsa-github-generator#3031]
**Describe the bug**

I'm attempting to publish a new version of the Python [`id`](https://github.com/di/id) package, using the package's GitHub Actions [release workflow](https://github.com/di/id/actions/workflows/release.yml).

This is what our current provenance generation step looks like:

```yaml
  generate-provenance:
    needs: [build]
    name: Generate build provenance
    permissions:
      actions: read   # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    # Currently this action needs to be referred by tag. More details at:
    # https://github.com/slsa-framework/slsa-github-generator#verification-of-provenance
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.9.0
    with:
      attestation-name: provenance-id-${{ github.event.release.tag_name }}.intoto.jsonl
      base64-subjects: "${{ needs.build.outputs.hashes }}"
      compile-generator: true # Workaround for https://github.com/slsa-framework/slsa-github-generator/issues/1163
      upload-assets: true
```

When our release workflow is triggered, this step runs as expected, and the interior `detect-env` and `generator` steps appear to succeed. The `upload-assets` step is then skipped, and `final` fails opaquely (apparently checking some kind of success state, without an error message):

```
  echo "outcome=$([ "$SUCCESS" == "true" ] && echo "success" || echo "failure")" >> "$GITHUB_OUTPUT"
  [ "$CONTINUE" == "true" ] || [ "$SUCCESS" == "true" ] || exit 27
```

You can see that in the release workflow logs here: https://github.com/di/id/actions/runs/7184211112/job/19564897464

This error persists even when the job is re-run.

**To Reproduce**

I don't have an easy reproducer, unfortunately. I'm happy to perform debugging steps on the `di/id` repository, however.

**Expected behavior**

I expected the `generate-provenance` step to succeed, as it has for previous release runs.
