### ISSUE TITLE
Examples on using generic provenance for containers

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#332]
- [x] Example for generating provenance and storing in ghcr.io (#390)
- [x] Examples of policy verification with [Kyverno](https://kyverno.io/) (#389)
- [ ] Examples of policy verification with [OPA](https://www.openpolicyagent.org/) (#388)

**Comment by ianlewis** [comment]
This should have a full example with policy verification using [OPA](https://www.openpolicyagent.org/) and/or [Kyverno](https://kyverno.io/).

**Comment by chipzoller** [comment]
If you can provide some suggestions on what such policies should check for, I can create and contribute them from Kyverno's side.

**Comment by ianlewis** [comment]
@chipzoller I think that, for starters, we need a policy that verifies the `invocation.entryPoint` is the full path to the generic workflow.

**Comment by ianlewis** [comment]
I'm working on figuring out how verification will work when using the generic workflow w/ containers. Based on the [Kyverno docs](https://kyverno.io/docs/writing-policies/verify-images/) it seems like Kyverno supports a `verifyImage` rule that can verify image signatures or image provenance and that it verifies it in whatever format `cosign attest` saves it in.

I'm guessing that a user's GH Actions workflow would look something like the following:
1. Build the docker image
2. Push it to the registry
3. Generate the provenance by passing the sha256 `RepoDigest` to the generic workflow
4. Upload the provenance to the registry using `cosign upload blob`

...but I need to check what the `cosign attest` API does and if I can mimic it with the provenance generated by the generic workflow and `cosign upload blob`.

**Comment by chipzoller** [comment]
Take a look at the work I've already done [here](https://github.com/chipzoller/zulu/blob/main/.github/workflows/slsa-generic-keyless.yaml). The first of three attestations happens [here](https://github.com/chipzoller/zulu/blob/1c3a746af484ec5c61a3c4e156f757caa0b5b639/.github/workflows/slsa-generic-keyless.yaml#L156). When using `cosign attest` on an image, as you've noted in another issue, it'll set the subject to something like

```json
  "subject": [
    {
      "name": "ghcr.io/chipzoller/zulu",
      "digest": {
        "sha256": "5365f368065f3e93629b71b404d75c03154be84ed9853a2ea6739d6994a1993e"
      }
    }
  ],
```

You therefore want all attestations to have the same subject, and that's why I'm stripping just the raw predicate out of the in-toto attested form [here](https://github.com/chipzoller/zulu/blob/1c3a746af484ec5c61a3c4e156f757caa0b5b639/.github/workflows/slsa-generic-keyless.yaml#L135). If that isn't done, the subjects will be different on account of the generic provenance generator producing a different subject. You can see [here](https://github.com/chipzoller/zulu/blob/1c3a746af484ec5c61a3c4e156f757caa0b5b639/.github/workflows/slsa-generic-keyless.yaml#L48) where I even customize the input name (for experimentation) knowing that it'll get stripped and replaced in the later step.

So, ideally, whenever the provenance generator for container images is made available, it should produce either the raw predicate (unattested form) allowing to be used as an input to `cosign attest --type slsaprovenance`, and/or in in-toto attested form the subject should be in alignment with what cosign would itself set if it handled the attestation.

**Comment by chipzoller** [comment]
## Sample Kyverno Policies with Keyless Verification

All the below Kyverno policies are set to `enforce` mode under `spec.validationFailureAction` meaning if the validation does not pass, it will block the creation or update of the Pod. Also, by default, these policies will work similarly for Pod controllers (Deployments, DaemonSets, StatefulSets, Jobs, and CronJobs) as they do for "bare" Pods. No other work is required. These policies will also resolve mutable tags to immutable digest format. Please see comment blocks for portions of the policies which need user customization.

1. Example policy that verifies the `invocation.configSource.uri` is a URI for the user's repo with the expected branch.
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-slsa-attestations
spec:
  validationFailureAction: enforce
  webhookTimeoutSeconds: 30
  rules:
    - name: check-uri-keyless
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        # Replace with your image. Wildcard values are supported.
        - "myreg.org/path/repo:*"
        attestors:
        - entries:
          - keyless:
            # In the case of GitHub Actions, the subject will be set to your Actions workflow responsible
            # for kicking off the process. Note that this will not be set to the external action
            # responsible for the provenance generation.
              subject: "https://github.com/myname/myrepo/.github/workflows/my-workflow.yaml@refs/heads/mybranch"
              issuer: "https://token.actions.githubusercontent.com"
        attestations:
        - predicateType: https://slsa.dev/provenance/v0.2
          conditions:
          - all:
            # The invocation.configSource.uri in the attestation will be set to the repository
            # and branch where your workflow, in the case of GitHub Actions, is located.
            # Replace with your values.
            - key: "{{ invocation.configSource.uri }}"
              operator: Equals
              value: "git+https://github.com/myname/myrepo@refs/heads/mybranch"
```

2. Check that `invocation.configSource.entryPoint` is the user's expected workflow.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-slsa-attestations
spec:
  validationFailureAction: enforce
  webhookTimeoutSeconds: 30
  rules:
    - name: check-entrypoint-keyless
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        # Replace with your image. Wildcard values are supported.
        - "myreg.org/path/repo:*"
        attestors:
        - entries:
          - keyless:
            # In the case of GitHub Actions, the subject will be set to your Actions workflow responsible
            # for kicking off the process. Note that this will not be set to the external action
            # responsible for the provenance generation.
              subject: "https://github.com/myname/myrepo/.github/workflows/my-workflow.yaml@refs/heads/mybranch"
              issuer: "https://token.actions.githubusercontent.com"
        attestations:
        - predicateType: https://slsa.dev/provenance/v0.2
          conditions:
          - all:
            # The invocation.configSource.entryPoint in the attestation will be set to the full
            # path to your workflow. With GitHub Actions, this will begin with .github/
            # Replace with your values.
            - key: "{{ invocation.configSource.entryPoint }}"
              operator: Equals
              value: ".github/workflows/my-workflow.yaml"
```

3. Check that the `builder.id` is a URI for the generic workflow.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-slsa-attestations
spec:
  validationFailureAction: enforce
  webhookTimeoutSeconds: 30
  rules:
    - name: check-builder-id-keyless
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        # Replace with your image. Wildcard values are supported.
        - "myreg.org/path/repo:*"
        attestors:
        - entries:
          - keyless:
            # In the case of GitHub Actions, the subject will be set to your Actions workflow responsible
            # for kicking off the process. Note that this will not be set to the external action
            # responsible for the provenance generation.
              subject: "https://github.com/myname/myrepo/.github/workflows/my-workflow.yaml@refs/heads/mybranch"
              issuer: "https://token.actions.githubusercontent.com"
        attestations:
        - predicateType: https://slsa.dev/provenance/v0.2
          conditions:
          - all:
            # This expression uses a regex pattern to ensure the builder.id in the attestation is equal to the official
            # SLSA provenance generator workflow and uses a tagged release in semver format. If using a specific SLSA
            # provenance generation workflow, you may need to adjust the first input as necessary.
            - key: "{{ regex_match('^https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@refs/tags/v[0-9].[0-9].[0-9]$','{{ builder.id}}') }}"
              operator: Equals
              value: true
```

## Keyed Verification

For any of the above policies, if a user wishes to verify them with key-based signing as opposed to keyless, they can simply substitute the `attestors[].entries[].keyless` block with the `keys[]` block below. There are no modifications needed to the `attestations` object.

```yaml
          - keys:
              publicKeys: |
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2kCXNpRME7TtCbzLNyRhdZY5JvmC
                sAeNYYYg5LYpLdYjqtdfly54yEevhBGQUy0vn/tbSOptTnUNcNgnNaBlPg==
                -----END PUBLIC KEY-----
```
