### ISSUE TITLE
[feature] Run `go generate ./...` before build

### ISSUE THREAD

**Issue by OpenWaygate** [slsa-framework/slsa-github-generator#3874]
**Is your feature request related to a problem? Please describe.**
Some files need to be generated, which will be used in `go build`

**Describe the solution you'd like**
Add another field in `Configuration File`, such as `generate`, to allow user customize the generation.

```yaml
# Version for this file.
version: 1

generate: "./..." # go generate ./...
generate: ""      # leave empty to skip go generate
```

**Describe alternatives you've considered**

**Additional context**
