### ISSUE TITLE
[docs] Verifying provenance with Kyverno

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#389]
Docs on how to verify provenance generated by the generic workflow with [Kyverno](https://kyverno.io/).

Kyverno docs on verifying images is here: https://kyverno.io/docs/writing-policies/verify-images/

**Comment by ianlewis** [comment]
`cosign attest` sets the intoto statement's subject to the "repo" name which I assume is the image path (e.g. ghcr.io/ianlewis/myimage) and the repo sha256 digest. We should be able to reproduce how `cosign attest` works and allow it to work with Kyverno.
https://github.com/sigstore/cosign/blob/a2e1c1d1f3f1835d70e1138ca4ac6156215d20dd/pkg/cosign/attestation/attestation.go#L171-L179

Will test more early next week.

**Comment by chipzoller** [comment]
I'd be glad to provide assistance/review here.

**Comment by ianlewis** [comment]
I tested out Kyverno with the generic workflow and it currently doesn't work because of how we store the certificate use to sign the attestations. 

Kyverno seems to call [VerifyImageAttestations](https://github.com/sigstore/cosign/blob/e4bc4a95743bb38922246856d02d987d1272e199/pkg/cosign/verify.go#L587-L608) from the cosign API [here](https://github.com/kyverno/kyverno/blob/fbde1fbcbe6fbe6454c427f5e91ec0e045776f23/pkg/cosign/client.go#L25-L27).

I have the following cluster policy set:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-slsa-attestations
spec:
  validationFailureAction: enforce
  webhookTimeoutSeconds: 30
  rules:
    - name: check-all-keyless
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            # Replace with your image. Wildcard values are supported.
            - "ghcr.io/ianlewis/actions-test:*"
          attestors:
            - entries:
                - keyless:
                    subject: "https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@refs/tags/v1.1.1"
                    issuer: "https://token.actions.githubusercontent.com"
          attestations:
            - predicateType: https://slsa.dev/provenance/v0.2
              conditions:
                - all:
                    - key: "{{ invocation.configSource.uri }}"
                      operator: Equals
                      value: "git+https://github.com/ianlewis/actions-test@refs/tags/v0.0.11"
                    - key: "{{ invocation.configSource.entryPoint }}"
                      operator: Equals
                      value: ".github/workflows/generic-container.yaml"
                    - key: "{{ regex_match('^https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@refs/tags/v[0-9].[0-9].[0-9]$','{{ builder.id}}') }}"
                      operator: Equals
                      value: true
```

When I try to create the following Pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: actions-test
spec:
  containers:
    - name: actions-test
      image: ghcr.io/ianlewis/actions-test:v0.0.11
  restartPolicy: Never
```

I get the following error:
```shell
$ kubectl apply -f actions-test-pod.yaml 
Error from server: error when creating "actions-test-pod.yaml": admission webhook "mutate.kyverno.svc-fail" denied the request: 

resource Pod/default/actions-test was blocked due to the following policies

check-slsa-attestations:
  check-all-keyless: |-
    failed to verify signature for ghcr.io/ianlewis/actions-test:v0.0.11: .attestors[0].entries[0].keyless: no matching attestations:
    no certificate found on attestation
```

I'm not sure yet why it's failing but I suspect it has to do with [how we are storing the cert w/ Rekor](https://github.com/slsa-framework/slsa-github-generator/blob/024238bc10cc620be603a7f5329be7a672171ba7/signing/sigstore/rekor.go#L67-L86).

It's the same error you get locally if you try to verify using keyless:
```shell
$ COSIGN_EXPERIMENTAL=1 cosign verify-attestation ghcr.io/ianlewis/actions-test:v0.0.11
Error: no matching attestations:
no certificate found on attestation
main.go:52: error during command execution: no matching attestations:
no certificate found on attestation
```
