### ISSUE TITLE
Github Job only producing one intoto.jsonl file

### ISSUE THREAD

**Issue by zurrehma** [slsa-framework/slsa-github-generator#566]
I have Github build running which is building three docker images, for each docker image I want attestation.intoto.jsonl file but I am only getting one file in Artifacts. Is it due to static name and overriding happening? if so, how can I change the file name since I am not seeing the attestaion-name var in [input](https://github.com/slsa-framework/slsa-github-generator/blob/v1.1.0/.github/workflows/generator_generic_slsa3.yml#L31)

How can I produce three intoto.jsonl for three docker images in one build?

**Comment by laurentsimon** [comment]
Thanks for the report. The generic generator is not officially released, please see https://github.com/slsa-framework/slsa-github-generator#generation-of-provenance

We are going to release this week. We have added support for the user to provide an attestation-name.

Note that we workflow only outputs a single attestation, and it has the attestation for all the artifacts you pass in `base64-subjects`.

Is there a reason that would not work for your use case?

**Comment by laurentsimon** [comment]
your example is correct if you want 3 different attestation files. Some points:

Note: You can use a single call to the re-usable workflow if a single attestation file is enough for your use case (the attestation will attest to the 3 hashes instead of 1). 

Too verify the provenance, use https://github.com/slsa-framework/slsa-verifier. You can pass `--print-provenance` and pipe that into `jq` to see the provenance after it's been verified: `slsa-verifier -provenance <> -source github.com/your/repo --print-provenance | jq`.

To read the raw provenance yourself, you can use `cat example.intoto.jsonl | jq -r '.payload' | base64 -d | jq`

**Comment by zurrehma** [comment]
slsa-verifier gives an error when I don't provide -artifact-path?

**Comment by laurentsimon** [comment]
yes, that's intended. If you want the verifier to be able to verify a container and pull the provenance automatically from the registry, you'll have to use the "container generator" instead. We're working on it and will release in Aug-Sept (see https://github.com/slsa-framework/slsa-github-generator#provenance-only-generators)

**Comment by ianlewis** [comment]
@zurrehma As @laurentsimon mentioned, in order to be able to verify container images you need to use the new "container generator" workflow.
See the doc here: https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/container

Note that while this is experimental, you should be able to test it out with a workflow like the following:

```yaml
generate-init-image-provenance:
  needs: [push-init-image]
  permissions:
    actions: read # for detecting the Github Actions environment.
    id-token: write # for creating OCID tokens for signing.
    packages: write # for uploading attestations.
  # TODO(https://github.com/slsa-framework/slsa-github-generator/issues/492): Use a tagged release once we have one.
  uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@main
  with:
    image: ${{ needs.push-init-image.outputs.tag }}
    digest: ${{ needs.push-init-image.outputs.digest }}
    registry-username: ${{ env.REGISTRY_USERNAME }}
    # TODO(https://github.com/slsa-framework/slsa-github-generator/issues/492): Remove after GA release.
    compile-generator: true
  secrets:
    registry-password: ${{ secrets.REGISTRY_PASSWORD }}

generate-image-provenance:
  needs: [push-image]
  permissions:
    actions: read # for detecting the Github Actions environment.
    id-token: write # for creating OCID tokens for signing.
    packages: write # for uploading attestations.
  # TODO(https://github.com/slsa-framework/slsa-github-generator/issues/492): Use a tagged release once we have one.
  uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@main
  with:
    image: ${{ needs.push-image.outputs.tag }}
    digest: ${{ needs.push-image.outputs.digest }}
    registry-username: ${{ env.REGISTRY_USERNAME }}
    # TODO(https://github.com/slsa-framework/slsa-github-generator/issues/492): Remove after GA release.
    compile-generator: true
  secrets:
    registry-password: ${{ secrets.REGISTRY_PASSWORD }}

generate-image-cli-provenance::
  needs: [push-image-cli]
  permissions:
    actions: read # for detecting the Github Actions environment.
    id-token: write # for creating OCID tokens for signing.
    packages: write # for uploading attestations.
  # TODO(https://github.com/slsa-framework/slsa-github-generator/issues/492): Use a tagged release once we have one.
  uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@main
  with:
    image: ${{ needs.push-image-cli.outputs.tag }}
    digest: ${{ needs.push-image-cli.outputs.digest }}
    registry-username: ${{ env.REGISTRY_USERNAME }}
    # TODO(https://github.com/slsa-framework/slsa-github-generator/issues/492): Remove after GA release.
    compile-generator: true
  secrets:
    registry-password: ${{ secrets.REGISTRY_PASSWORD }}
```

The image attestations can then be verified using `cosign`

```shell
$ export COSIGN_EXPERIMENTAL=1
$ cosign verify-attestation --type slsaprovenance [INIT_IMAGE]
$ cosign verify-attestation --type slsaprovenance [IMAGE]
$ cosign verify-attestation --type slsaprovenance [IMAGE_CLI]
```

We are working on adding support to `slsa-verifier` for container in https://github.com/slsa-framework/slsa-verifier/issues/92

You can follow progress via the milestone for the container generator workflow GA here: https://github.com/slsa-framework/slsa-github-generator/milestone/3
