### ISSUE TITLE
[feature] Share builder's code

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#684]
We talked about it in the past, and I recall we created an issue about it. I cannot find this issue so I'm creating this one. If you find it, let me know and I'll close this one and add a new comment to the original issue.

The idea is to help scale writing of new builders by sharing the builder code by have a configuration option for each ecosystem. This config file would be internal to the builders. Each workflow would pass variables provided by developer and the config file to indicate the ecosystem we're building for.

Example of config file (npm):
```yaml
- version: 1
- build-steps: # untrusted, come from developer
   - name: download dependencies
      cmd:
       - npm
       - ci
     env:
       - X=bla
       - Y=hi
    - name: run scripts
      cmd:  
         - npm 
         - run # developer would pass scrip1t, script2, etc and the builder would append this to the command
    - name: create tarball
       cmd:
         - npm
         - pack

publish-steps:
   - name: publish
      cmd:
       - npm
       - publish
```

Example of config file (mvn):
```yaml
- version: 1
- build-steps:  # untrusted, come from developer
   - name: create package
      cmd:
       - mvn
       - package
    
publish-steps:
   - name: sign
      cmd:
       - pgp 
  - name: publish
     cmd:
       - mvn
       - publish
```

The common builder code would load and execute these commands. (First it would `cd` to a directory if needed -  defined as a workflow input). The workflow can also pass additional variables to each step, that will be appended to the command. For build steps, these will come from user and will be untrusted. For publish steps, it would be provided by the workflow. Note that the publish steps may not always be present, since there are ecosystem GHA that already exists and that we could re-use.

/cc @loosebazooka @asraa @ianlewis @sethmlarson @joshuagl
