### ISSUE TITLE
[doc] Add example for workflows that use strategy / matrix

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#707]
Here is an example https://github.com/google/sentencepiece/blob/master/.github/workflows/wheel.yml

**Comment by pnacht** [comment]
I think I might've come up with a solution that requires less duplication and hard-coding.

The workflow becomes effectively:

```yml
jobs:
  build:
    strategy:
      matrix:
        java_version: ["8", "11", "17"]
        foo: ["a", "b"]
    outputs:
      # We unfortunately still need one unique output per permutation.
      # However, the names themselves are irrelevant.
      # The key-names chosen here are for demonstrative purposes, I'd recommend
      # something a bit more descriptive in actual code!
      lorem:       ${{ steps.hash.outputs.hash-8-a }}
      ipsum:       ${{ steps.hash.outputs.hash-11-a }}
      dolor:       ${{ steps.hash.outputs.hash-17-a }}
      sit:         ${{ steps.hash.outputs.hash-8-b }}
      amet:        ${{ steps.hash.outputs.hash-11-b }}
      consectetur: ${{ steps.hash.outputs.hash-17-b }}
    steps:
      - ...
      - name: Build
        # ...

      # each iteration must define a unique key in the steps.hash.outputs map
      - name: Generate subject
        id: hash
        run: |
          echo "hash-${{ matrix.java_version }}-${{ matrix.foo }}=$( \
            sha256sum ... | base64 -w0 \
          )" >> "$GITHUB_OUTPUT"

  # This step collates all of the different hashes into a single base64 string.
  # Note that the individual hash names don't have to be duplicated here;
  # this is indifferent to the quantity, names or types of permutations.
  combine_hashes:
    needs: [build]
    outputs:
      hashes: ${{ steps.hashes.outputs.hashes }}
    env:
      HASHES: ${{ toJSON(needs.build.outputs) }}
    steps:
      - id: hashes
        run: |
          echo "$HASHES" | jq -r '.[] | @base64d' | sed "/^$/d" > hashes.txt
          echo "hashes=$(cat hashes.txt | base64 -w0)" >> "$GITHUB_OUTPUT"

  # the provenance job is unchanged, other than relying on combine_hashes
  provenance:
    needs: [combine_hashes]
    # ...
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.2.2
    with:
      base64-subjects: "${{ needs.combine_hashes.outputs.hashes }}"
```

If the build job must output something else other than hashes, then the keys for the hashes should follow a given format that can be identified via a regex in the call to `jq` within `combine_hashes`, modifying it to

```bash
# assuming all hashes are stored in needs.build.outputs.[hash-$java_version-$foo]
... | jq -r 'with_entries(select(.key | match("hash-.*-.*")))[] | base64d' | ...
```

For a working example, see [this workflow](https://github.com/pnacht/jackson-core/blob/matrix_build/.github/workflows/main.yml) (in the matrix_build branch of my [fork of jackson-core](https://github.com/pnacht/jackson-core)) and [this successful workflow run](https://github.com/pnacht/jackson-core/actions/runs/3499273310).
