### ISSUE TITLE
[feature] bring your own builder

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#763]
it may be a useful component for others to create provenance with the same format across GH builders.
See https://github.com/sigstore/fulcio/issues/754#issuecomment-1227505585

**Comment by laurentsimon** [comment]
Something I wanted to note is that re-usable workflows cannot call each other. So on GH, it may not be feasible to separate the "builder"  and "generator" as different "trusted entities". Which is why I'm proposing a GHA to ensure the same provenance format. The. original thread (https://github.com/sigstore/fulcio/issues/754) suggested that, but It's not currently possible, AFAIK

**Comment by znewman01** [comment]
Ahh, yeah per @laurentsimon's comment upthread, what I want isn't possible on GitHub. I'm glad I wrote it down, though. Maybe a FR for GitHub Actions?

**Comment by znewman01** [comment]
Oh, and 

> Something I wanted to note is that re-usable workflows cannot call each other

may not be true anymore (as of 3 days ago): https://docs.github.com/en/actions/using-workflows/reusing-workflows#nesting-reusable-workflows

I still don't think this gets us what we want (see my comment above).

**Comment by laurentsimon** [comment]
Great find! it may give us what we want!

**Comment by laurentsimon** [comment]
> Really what I want is a generic provenance generator that wraps other compilation actions: you would give it some-org/nodejs-builder@ABCDEF as an input, and it would call that. Then, it would look grab an artifact from a standard location.

That's basically what we do in our generators. Except that we use VM within the same workflow for the generator and the builder. Within our trusted workflow, we can call an *external* trusted builder via a GitHub action. Today we only call internal ones, but it's technically do-able to call external ones.

**Comment by znewman01** [comment]
Very cool! I think that would do what I'm looking for 🚀

**Comment by ianlewis** [comment]
Responding to the comments on the previous issue.

> > Plus, now there's one provenance generator for _each_ ecosystem that needs to be audited. Even if we're reusing components, there's not an easy way to check "my provenance came from a trusted generator, even if the builder is bad" without going into the source of the builder and parsing the workflow.
> 
> I think the plan is to share the provenance generation code with other builders for a given CI. On GitHub, we could theoretically create an Action for this. /cc @ianlewis

For a single build service with some common info this is doable. It becomes a lot harder when talking about completely different build services that might have very different data and methods for retrieving the trusted data from the builder. So doable for GitHub Actions. Much less doable for other build services like Gitlab etc.

> "my provenance came from a trusted generator, even if the builder is bad" without going into the source of the builder and parsing the workflow.

IIUC This is a requirement of SLSA 3's Non-falsifiable provenance requirement. i.e. builds have to be isolated from the provenance generation such that build service users cannot change the provenance. In practice this means there must be a hard security boundary between the user's actual build code, and the provenance generator. In the case of slsa-github-generator we [use different GHA jobs and thus different VMs](https://github.com/slsa-framework/slsa-github-generator/blob/main/SPECIFICATIONS.md).
https://slsa.dev/spec/v0.1/requirements#non-falsifiable

Generally I expect SLSA 3 builders to implement this functionality and thus you should be able to be determine this via the `builder.id`.

**Comment by laurentsimon** [comment]
This feature is also useful to onboard scanner, like Syft. We'd just run their CLI and attest to the output.
/cc @lumjjb

**Comment by laurentsimon** [comment]
What would be even better is if we could turn an existing GHA into an attested one. This may be possible as well. If the input to our workflow is an action, we dynamically generate the call to the action.

**Comment by laurentsimon** [comment]
A simpler solution to start with could be to operate a service like https://github.com/actions/starter-workflows, but for SLSA. Ask interested builders, scanners, etc to submit a config file that describes the input, output, and commands to run.

**Comment by ianlewis** [comment]
I also thought about a "command" workflow that would run a command or set of commands and attest to some output. I like the idea of turning an existing GHA into an attested one but I wonder if we can get enough info from outside of the workflow.

**Comment by asraa** [comment]
For subject output measurement: this would require one of
1. User specifying some output to measure for subject
2. Measure the output files of some workflow directly

I like (2) a lot in the case that we have an existing GHA. 

For a CLI: we would have to resort to (1)

**Comment by laurentsimon** [comment]
Would we have a config file on our repo, on the user's repo... or everything via workflow input parameters?

**Comment by laurentsimon** [comment]
Something to think about: where do we store the artifact type? DSSE? Intoto predicate type? Inside the `buildConfig`?

**Comment by laurentsimon** [comment]
Another angle to think about is branding. For an ecosystem like npm, users will be more receptive if the re-usable workflow is located on an npm org / repository, rather than in the slsa-framework repo. However, building re-usable workflow is hard, takes time and requires maintenance. Given the re-usable workflows can call each other now, we could have:
1. npm/npm/.github/workflows/build-and-publish.yml. Users call this re-usable workflow. This re-usable acts as a proxy and simply calls a re-usable workflow hosted on our repository, using some lower-level arguments, such as the "type" of predicate (SBOM, scanner, etc), a path to the binary, the command to run.
2. slsa-frameowk/slsa-github-generator/.github/workflows/builder_node_slsa3.yml does all the work, and can report the arguments (binary, command) in the provenance. For different type of artifacts (SBOM, scans and different vendors (Syft, Trivvy)), we'd need to agree on a type `type: sbom/syft/whatever`, `scan/syft/syft-scan-type` or something to this effect.

**Comment by laurentsimon** [comment]
Here's a way we can implement this feature, at a high-level. Let's say goreleaser if the builder / toolchain here.

Goreleaser maintainers create a re-usable workflow to wrap their Action, say at https://github.com/goreleaser/goreleaser-action/tree/master/.github/workflows/builder.yml

This workflow looks roughly like the following (I've omitted a lot of details for simplicity):
```yaml
   # Checkout developer repository to scan / build / create SBOM for.
    - uses: actions/checkout@xxx
    
    # Run the action. 
    - uses: goreleaser/goreleaser-action
      with:
        ...
   
    # Create SLSA subjects
    - id: hash
      env:
ARTIFACTS: ...
      run: |
        checksum_file=$(sha256sum "$ARTIFACT")
        echo "::set-output name=hashes::$(echo "$checksum_file" | base64 -w0)"

slsa-attest:
   needs: [run-tool]
   uses: slsa-framework/slsa-github-generator/path/to/some_workflow.yml@v1.2.3
   with:
     base64-subjects: ${{ needs.run-tool.outputs.hashes }}
     args: <>
```

Users of Goreleaser can use the https://github.com/goreleaser/goreleaser-action/tree/master/.github/workflows/builder.yml instead of calling the Action.

From Goreleaser's point of view:
- they keep full control of how their build works.
- they don't have to re-invent the wheel for signing or creating SLSA provenance: they just use our service
- their users never see the slsa-github-generator repository, and don't need to know about it.

We would need to decide what the format of the provenance looks like, so that we can report the re-usable workflow that called us *inside* the provenance. Here's a possible format to get the ball rolling:

```yaml
  "buildConfig": {
      "version": 1,
      "builder": {
           "id":  "https://github.com/goreleaser/goreleaser-action/tree/master/.github/workflows/builder.yml@refs/tags/v1.2.0",
           "sha1": "abcdef...",
           "type": "delegatedReusableWorkflow",
        },
       // Optional steps or buildConfig (?)
      "steps": {
           "https://github.com/goreleaser/goreleaser-action.yaml@v1.2.3",
           "argument1", "argument1-value", etc
       }
```

**Comment by laurentsimon** [comment]
Something that's not covered in the above provenance is when there are several re-usable workflow involved. Say:
```
developer -> org-reusable-workflow -> gorleaser-reusable-workflow -> slsa-github-generator
                                                               -> scan-reusable-workflow  -> slsa-github-generator
                                                               -> slsa-github-generator (to sign an SBOM)
```

Do we want to support this? What would the provenance format look like?

@ckotzbauer please chime in if you have some advice / ideas.

**Comment by znewman01** [comment]
Broadly, that plan makes a lot of sense!

The main hesitation I have is just that there's a lot of copy-paste involved in the wrapper reusable workflow, which makes it harder for a verifier to audit whether it's trusted. Not sure we can do anything about that without some big enhancements to GH Actions.

**Comment by vlsi** [comment]
```yaml
    # Create SLSA subjects
    - id: hash
      env:
        ARTIFACTS: ...
      run: |
        checksum_file=$(sha256sum "$ARTIFACT")
        echo "::set-output name=hashes::$(echo "$checksum_file" | base64 -w0)"
```

Is there a "standard" format for it?
In other words, does `slsa-framework/slsa-github-generator` consume just a list of hashes?
Is the hash sha256 always or is it "bytes + algorithm"?
