### ISSUE TITLE
question: allow provenance generation workflow to hash artifacts?

### ISSUE THREAD

**Issue by imjasonh** [slsa-framework/slsa-github-generator#879]
Sorry if this has already been discussed and rejected, but reading https://slsa.dev/blog/2022/08/slsa-github-workflows-generic-ga and based on my understanding of GitHub Actions, it sounds like it should be possible to combine the `Generate hashes` step and the provenance generation step, if the provenance step takes a list of comma-separated paths to hash. For example:

```yaml
provenance:
  permissions:
    actions: read # Needed for detection of GitHub Actions environment.
    id-token: write # Needed for provenance signing and ID.
    contents: write # Needed for release uploads.
  uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@vX.Y.Z
  with:
    artifact-paths: artifact1,artifact2
```

Then the provenance step could run `sha256sum artifact1 artifact2 | base64 -w0` internally, and use it just as if the hash had been generated outside and passed in.

Is there some reason this wasn't considered?
